name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: make install

    - name: Run check
      run: make unit-test

    - name: Run distcheck
      run: make e2e-test
